/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParentPortalRouteImport } from './routes/parent-portal'
import { Route as ParentAuthRouteImport } from './routes/parent-auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminStudentsRouteImport } from './routes/_admin/students'
import { Route as AdminStaffRouteImport } from './routes/_admin/staff'
import { Route as AdminRolesRouteImport } from './routes/_admin/roles'
import { Route as AdminReportCardsRouteImport } from './routes/_admin/report-cards'
import { Route as AdminMessagesRouteImport } from './routes/_admin/messages'
import { Route as AdminInsightsRouteImport } from './routes/_admin/insights'
import { Route as AdminGradesRouteImport } from './routes/_admin/grades'
import { Route as AdminFeesRouteImport } from './routes/_admin/fees'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminAttendanceRouteImport } from './routes/_admin/attendance'
import { Route as AdminAnnouncementsRouteImport } from './routes/_admin/announcements'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const ParentPortalRoute = ParentPortalRouteImport.update({
  id: '/parent-portal',
  path: '/parent-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentAuthRoute = ParentAuthRouteImport.update({
  id: '/parent-auth',
  path: '/parent-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportCardsRoute = AdminReportCardsRouteImport.update({
  id: '/report-cards',
  path: '/report-cards',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGradesRoute = AdminGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/parent-auth': typeof ParentAuthRoute
  '/parent-portal': typeof ParentPortalRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/announcements': typeof AdminAnnouncementsRoute
  '/attendance': typeof AdminAttendanceRoute
  '/dashboard': typeof AdminDashboardRoute
  '/fees': typeof AdminFeesRoute
  '/grades': typeof AdminGradesRoute
  '/insights': typeof AdminInsightsRoute
  '/messages': typeof AdminMessagesRoute
  '/report-cards': typeof AdminReportCardsRoute
  '/roles': typeof AdminRolesRoute
  '/staff': typeof AdminStaffRoute
  '/students': typeof AdminStudentsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/parent-auth': typeof ParentAuthRoute
  '/parent-portal': typeof ParentPortalRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/announcements': typeof AdminAnnouncementsRoute
  '/attendance': typeof AdminAttendanceRoute
  '/dashboard': typeof AdminDashboardRoute
  '/fees': typeof AdminFeesRoute
  '/grades': typeof AdminGradesRoute
  '/insights': typeof AdminInsightsRoute
  '/messages': typeof AdminMessagesRoute
  '/report-cards': typeof AdminReportCardsRoute
  '/roles': typeof AdminRolesRoute
  '/staff': typeof AdminStaffRoute
  '/students': typeof AdminStudentsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/parent-auth': typeof ParentAuthRoute
  '/parent-portal': typeof ParentPortalRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_admin/announcements': typeof AdminAnnouncementsRoute
  '/_admin/attendance': typeof AdminAttendanceRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/fees': typeof AdminFeesRoute
  '/_admin/grades': typeof AdminGradesRoute
  '/_admin/insights': typeof AdminInsightsRoute
  '/_admin/messages': typeof AdminMessagesRoute
  '/_admin/report-cards': typeof AdminReportCardsRoute
  '/_admin/roles': typeof AdminRolesRoute
  '/_admin/staff': typeof AdminStaffRoute
  '/_admin/students': typeof AdminStudentsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/parent-auth'
    | '/parent-portal'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/announcements'
    | '/attendance'
    | '/dashboard'
    | '/fees'
    | '/grades'
    | '/insights'
    | '/messages'
    | '/report-cards'
    | '/roles'
    | '/staff'
    | '/students'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/parent-auth'
    | '/parent-portal'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/announcements'
    | '/attendance'
    | '/dashboard'
    | '/fees'
    | '/grades'
    | '/insights'
    | '/messages'
    | '/report-cards'
    | '/roles'
    | '/staff'
    | '/students'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/auth'
    | '/mcp'
    | '/parent-auth'
    | '/parent-portal'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_admin/announcements'
    | '/_admin/attendance'
    | '/_admin/dashboard'
    | '/_admin/fees'
    | '/_admin/grades'
    | '/_admin/insights'
    | '/_admin/messages'
    | '/_admin/report-cards'
    | '/_admin/roles'
    | '/_admin/staff'
    | '/_admin/students'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ParentAuthRoute: typeof ParentAuthRoute
  ParentPortalRoute: typeof ParentPortalRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parent-portal': {
      id: '/parent-portal'
      path: '/parent-portal'
      fullPath: '/parent-portal'
      preLoaderRoute: typeof ParentPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-auth': {
      id: '/parent-auth'
      path: '/parent-auth'
      fullPath: '/parent-auth'
      preLoaderRoute: typeof ParentAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/students': {
      id: '/_admin/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/staff': {
      id: '/_admin/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/roles': {
      id: '/_admin/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/report-cards': {
      id: '/_admin/report-cards'
      path: '/report-cards'
      fullPath: '/report-cards'
      preLoaderRoute: typeof AdminReportCardsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/messages': {
      id: '/_admin/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/insights': {
      id: '/_admin/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/grades': {
      id: '/_admin/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AdminGradesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/fees': {
      id: '/_admin/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/attendance': {
      id: '/_admin/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/announcements': {
      id: '/_admin/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminGradesRoute: typeof AdminGradesRoute
  AdminInsightsRoute: typeof AdminInsightsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminReportCardsRoute: typeof AdminReportCardsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminGradesRoute: AdminGradesRoute,
  AdminInsightsRoute: AdminInsightsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminReportCardsRoute: AdminReportCardsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminStudentsRoute: AdminStudentsRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ParentAuthRoute: ParentAuthRoute,
  ParentPortalRoute: ParentPortalRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
